[package]
name = "coding-agent"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
ratatui = "0.29.0"
anyhow = "1.0.100"
rig-core = "0.26.0"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
dotenv = "0.15.0"
