[package]
name = "coding-agent"
version = "0.1.0"
edition = "2024"

[dependencies]
rig-core = "0.26.0"
serde_json = "1.0.145"
tree-sitter = "0.26.2"
tree-sitter-python = "0.25.0"
tree-sitter-rust = "0.24.0"
